/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/3dModels/liberLetters.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/liberLetters.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.L.geometry} material={materials['Material.004']} position={[-0.921, 0.819, -0.132]} rotation={[2.001, 0.467, -0.101]} />
      <mesh geometry={nodes.i.geometry} material={materials['Material.003']} position={[2.924, 0.586, -0.477]} rotation={[1.141, 0, 0]} />
      <mesh geometry={nodes.d.geometry} material={materials['Material.005']} position={[1.044, 0.91, 3.986]} rotation={[0.954, -0.118, -2.977]} />
      <mesh geometry={nodes.e.geometry} material={materials['Material.002']} position={[0.509, 2.765, 1.323]} rotation={[2.916, -1.181, -3.018]} />
      <mesh geometry={nodes.r.geometry} material={materials['Material.001']} position={[1.541, 0.997, -0.771]} rotation={[1.365, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/liberLetters.glb')
