const { model, Schema } = require('mongoose');

const authorSchema = new Schema({
  name: String
});

const bookSchema = new Schema({
  // _id is autogenerated by mongoose
  title: String,
  // reason why it's a string is bc although number comes from fetch, Mongoose makes it a string when making a new book in db.
  bookId: { type: String, unique: true },
  authors: [authorSchema],
  image: {
    data: String,
    contentType: String
  },
  text: String,
  reviews: [
    {
      type: Schema.Types.Mixed,
      ref: 'Review'
    }
  ]
});

const Book = model('Book', bookSchema);

module.exports = Book;